services:
    app.event.language:
        class: Purethink\CMSBundle\EventListener\LanguageListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setLocale }
        arguments: ['@service_container']

    app.event.component:
        class: Purethink\CMSBundle\EventListener\ComponentListener
        public: false
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    app.event.extension_has_field:
        class: Purethink\CMSBundle\EventListener\ExtensionHasFieldListener
        public: false
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postFlush }

    app.event.contact:
        class: Purethink\CMSBundle\EventListener\ContactListener
        arguments: ['@service_container']
        public: false
        tags:
            - { name: doctrine.event_listener, event: prePersist }