services:
    app.event.language:
        class: Purethink\CMSBundle\EventListener\LanguageListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setLocale }
        arguments: ['@app.language_service']

    app.event.component:
        class: Purethink\CMSBundle\EventListener\ComponentListener
        public: false
        tags:
            - { name: doctrine.event_listener, event: prePersist }
