twig:
    form:
        resources:
            - 'SonataMediaBundle:Form:media_widgets.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'

doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
            oneLocale:
                class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
                enabled: true

stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            timestampable: true
            sluggable: true
            sortable: true
            softdeleteable: true
            translatable: true

pix_sortable_behavior:
    position_field: ~

fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Purethink\CMSBundle\Entity\User
    group:
        group_class:   Purethink\CMSBundle\Entity\Group
    from_email:
        address: "%mailer_user%"
        sender_name: PureThink

sonata_admin:
    title: PureThink
    templates:
        layout: "PurethinkCMSBundle:Admin:layout.html.twig"
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }

        groups:
            sonata.admin.group.content:
                label: admin.dashboard.cms
                icon: <i class="fa fa-th"></i>
                label_catalogue: AppBundle
                items:
                    - app.admin.article
                    - app.admin.menu_type
                    - app.admin.extension
                    - app.admin.component
                    - app.admin.tag
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
            sonata.admin.group.contact:
                label: admin.dashboard.contact
                icon: <i class="fa fa-comment"></i>
                label_catalogue: AppBundle
                items:
                    - app.admin.contact
            sonata.admin.group.administration:
                label: sonata_administration
                icon: <i class="fa fa-cogs"></i>
                label_catalogue: SonataAdminBundle
                items:
                    - sonata.user.admin.user
                    - app.admin.language
                    - app.admin.site

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.block.service.text:
        sonata.user.block.account:
        sonata.user.block.menu:
            contexts: [user]
        app.block.language:
        app.block.menu:
        app.block.component:

sonata_media:
    class:
        media: Purethink\CMSBundle\Entity\Media
        gallery: Purethink\CMSBundle\Entity\Gallery
        gallery_has_media: Purethink\CMSBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                small: { width: 100, quality: 70 }
                big:   { width: 500, quality: 70 }
    cdn:
        server:
            path: /uploads/media
    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

sonata_user:
    class:
        user: Purethink\CMSBundle\Entity\User
        group: Purethink\CMSBundle\Entity\Group
    admin:
        user:
            class: Purethink\CMSBundle\Admin\UserAdmin
    impersonating:
        route: page
        parameters: { path: / }

    manager_type: orm

    profile:
        dashboard:
            blocks:
                - { position: left, type: sonata.block.service.text, settings: { content: "<h2>Welcome!</h2> This is a sample user profile dashboard, feel free to override it in the configuration! Want to make this text dynamic? For instance display the user's name? Create a dedicated block and edit the configuration!"} }
        menu:
            - { route: 'sonata_user_profile_show', label: 'sonata_profile_title', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_change_password', label: 'change_password', domain: 'SonataUserBundle'}
        form:
            type: sonata_user_profile
            handler: sonata.user.profile.form.handler.default
            name: sonata_user_profile_form
            validation_groups:
                - Profile
                - Default

ivory_ck_editor:
    default_config: default
    configs:
        default:
            toolbar: "cke_toolbar"
            height: "400px"
            filebrowserBrowseRoute: admin_purethink_cms_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_purethink_cms_media_ckeditor_browser
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_purethink_cms_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            filebrowserImageUploadRoute: admin_purethink_cms_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
        excerpt:
            toolbar: "cke_toolbar"
            height: "200px"
            filebrowserBrowseRoute: admin_purethink_cms_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_purethink_cms_media_ckeditor_browser
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_purethink_cms_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            filebrowserImageUploadRoute: admin_purethink_cms_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
    toolbars:
        configs:
            cke_toolbar : ['@clipboard', '@editing', '@links', '@insert', '@tools', '@document', '/', '@basicstyles', '@paragraph', '@styles', '@colors']
        items:
            clipboard   : ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
            editing     : ['Scayt']
            links       : ['Link', 'Unlink', 'Anchor']
            insert      : ['Image', 'Table', 'HorizontalRule',  'SpecialChar']
            tools       : ['Maximize']
            document    : ['Source']
            basicstyles : ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat']
            paragraph   : ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft',  'JustifyCenter', 'JustifyRight', 'JustifyBlock']
            styles      : ['Styles', 'Format']
            colors      : ['TextColor', 'BGColor']

a2lix_i18n_doctrine:
    manager_registry: doctrine

a2lix_translation_form:
    locales: [pl, en]

doctrine_migrations:
    table_name: cms_migration_versions