doctrine:
    orm:
        dql:
            datetime_functions:
                YEAR: DoctrineExtensions\Query\Mysql\Year
                MONTH: DoctrineExtensions\Query\Mysql\Month

knp_paginator:
    page_range: 10
    template:
        pagination: PurethinkCMSBundle:Pagination:sliding.html.twig