services:
    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    app.language_service:
        class: Purethink\CMSBundle\Service\Language
        arguments: ['@doctrine.orm.entity_manager']

    app.available_route:
        class: Purethink\CMSBundle\Service\AvailableRoute
        arguments: ['@router']

    app.contact_email:
        class: Purethink\CMSBundle\Service\ContactEmail
        arguments: ['@service_container','@doctrine.orm.entity_manager', '@mailer', '@templating']